# Generated by Django 5.2.1 on 2025-05-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('hometown', models.CharField(blank=True, max_length=50)),
                ('years_active', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('career_events_played', models.PositiveIntegerField(default=0)),
                ('career_wins', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
