# Generated by Django 5.2.1 on 2025-05-30 00:07

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('hometown', models.CharField(blank=True, max_length=50)),
                ('years_active', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='player_images/')),
                ('hof_inducted', models.BooleanField(default=False)),
                ('hof_year', models.PositiveIntegerField(blank=True, null=True)),
                ('accolades', models.TextField(blank=True)),
            ],
        ),
    ]
