# Generated by Django 5.2.1 on 2025-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accolades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hof_inducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='hof_year',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
