# Generated by Django 5.2.1 on 2025-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
