# Generated by Django 5.2.1 on 2025-06-23 20:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=4, null=True),
        ),
    ]
