# Generated by Django 5.2.1 on 2025-05-13 02:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_career_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='career_wins',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
