# Generated by Django 5.2.1 on 2025-05-29 21:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_career_events_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hof_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='player_images/'),
        ),
    ]
